name: comment-on-issue
run-name: add comment
on:
  issue_comment:
    types: [created]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: DeepKumbhare85/issue-comment-javascript-action@v1.1
        with:
          who-to-greet: "Deep kumbhare"
      - name: Get the output time
        run: |
          gh issue comment 1 --body "The time was ${{ steps.hello.outputs.time }}"
          gh issue comment 1 --body "my temp commit"
      - name: comment on issue
        run: |
          echo ${{ github.event.payload.issue.number }}
