name: comment-on-issue
run-name: add comment
on:
  issue_comment:
    types: [created]
jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: DeepKumbhare85/issue-comment-javascript-action@v1.1
        with:
          who-to-greet: "Mona the Octocat"
